In [1]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_train = pd.read_csv("./kaggle_data/titanic/train.csv")

In [69]:
df_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [89]:
X

PassengerId  Pclass    Sex   Age  SibSp  Parch  Ticket     Fare  Cabin  \
0              1       3  False  22.0      1      0       1   7.2500      0   
1              2       1   True  38.0      1      0       1  71.2833      3   
2              3       3   True  26.0      0      0       1   7.9250      0   
3              4       1   True  35.0      1      0       0  53.1000      3   
4              5       3  False  35.0      0      0       0   8.0500      0   
..           ...     ...    ...   ...    ...    ...     ...      ...    ...   
885          886       3   True  39.0      0      5       0  29.1250      0   
886          887       2  False  27.0      0      0       0  13.0000      0   
887          888       1   True  19.0      0      0       0  30.0000      2   
889          890       1  False  26.0      0      0       0  30.0000      3   
890          891       3  False  32.0      0      0       0   7.7500      0   

     Embarked  
0         3.0  
1         1.0  
2         3.0  
3         3.0  
4         3.0  
..        ...  
885       2.0  
886       3.0  
887       3.0  
889       1.0  
890       2.0  

[714 rows x 10 columns]

In [85]:
set([i[0] for i in df_train.Cabin if isinstance(i, str)])

{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [115]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler


X = df_train.drop("Name", axis=1)
X.replace({'Sex': {'female': True, 'male': False}}, inplace=True)
X.replace({'Embarked': {'C': 1, 'Q': 2, "S":3, np.nan:0}}, inplace=True)
cabin_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'T': 8}
X['Cabin'] = df_train['Cabin'].apply(lambda x: cabin_map.get(str(x)[0], 0) if pd.notnull(x) else 0)
X['Ticket'] = df_train['Ticket'].apply(lambda ticket: 0 if ticket.isdigit() else 1)
X = X.dropna()
y = X['Survived']
X = X.drop('Survived', axis=1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train logistic regression
model = LogisticRegression(max_iter=1000)
model.fit(X_scaled, y)

C:\Users\pietr\AppData\Local\Temp\ipykernel_19908\682494166.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({'Sex': {'female': True, 'male': False}}, inplace=True)
C:\Users\pietr\AppData\Local\Temp\ipykernel_19908\682494166.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({'Embarked': {'C': 1, 'Q': 2, "S":3, np.nan:0}}, inplace=True)


LogisticRegression(max_iter=1000)

In [99]:
y_pred = model.predict(X_scaled)
print("Confusion Matrix:\n", confusion_matrix(y, y_pred))
print("\nClassification Report:\n", classification_report(y, y_pred))

Confusion Matrix:
 [[363  61]
 [ 81 209]]

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.86      0.84       424
           1       0.77      0.72      0.75       290

    accuracy                           0.80       714
   macro avg       0.80      0.79      0.79       714
weighted avg       0.80      0.80      0.80       714



In [118]:

X = df_train.drop("Name", axis=1)
X.replace({'Sex': {'female': True, 'male': False}}, inplace=True)
X.replace({'Embarked': {'C': 1, 'Q': 2, "S":3, np.nan:0}}, inplace=True)
cabin_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'T': 8}
X['Cabin'] = df_train['Cabin'].apply(lambda x: cabin_map.get(str(x)[0], 0) if pd.notnull(x) else 0)
X['Ticket'] = df_train['Ticket'].apply(lambda ticket: 0 if ticket.isdigit() else 1)
# X = X.dropna()
y = X['Survived']
X = X.drop('Survived', axis=1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

C:\Users\pietr\AppData\Local\Temp\ipykernel_19908\1881375886.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({'Sex': {'female': True, 'male': False}}, inplace=True)
C:\Users\pietr\AppData\Local\Temp\ipykernel_19908\1881375886.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({'Embarked': {'C': 1, 'Q': 2, "S":3, np.nan:0}}, inplace=True)


In [119]:
from sklearn.tree import DecisionTreeClassifier


dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_scaled, y)

y_pred_dt = dt_model.predict(X_scaled)
print("Confusion Matrix:\n", confusion_matrix(y, y_pred_dt))
print("\nClassification Report:\n", classification_report(y, y_pred_dt))

Confusion Matrix:
 [[549   0]
 [  0 342]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       549
           1       1.00      1.00      1.00       342

    accuracy                           1.00       891
   macro avg       1.00      1.00      1.00       891
weighted avg       1.00      1.00      1.00       891



In [120]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_scaled, y)

y_pred_rf = rf_model.predict(X_scaled)
print("Confusion Matrix:\n", confusion_matrix(y, y_pred_rf))
print("\nClassification Report:\n", classification_report(y, y_pred_rf))

Confusion Matrix:
 [[549   0]
 [  0 342]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       549
           1       1.00      1.00      1.00       342

    accuracy                           1.00       891
   macro avg       1.00      1.00      1.00       891
weighted avg       1.00      1.00      1.00       891



In [121]:
X = df_test.drop("Name", axis=1)
X.replace({'Sex': {'female': True, 'male': False}}, inplace=True)
X.replace({'Embarked': {'C': 1, 'Q': 2, "S":3, np.nan:0}}, inplace=True)
cabin_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'T': 8}
X['Cabin'] = df_train['Cabin'].apply(lambda x: cabin_map.get(str(x)[0], 0) if pd.notnull(x) else 0)
X['Ticket'] = df_train['Ticket'].apply(lambda ticket: 0 if ticket.isdigit() else 1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

C:\Users\pietr\AppData\Local\Temp\ipykernel_19908\2957625884.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({'Sex': {'female': True, 'male': False}}, inplace=True)
C:\Users\pietr\AppData\Local\Temp\ipykernel_19908\2957625884.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({'Embarked': {'C': 1, 'Q': 2, "S":3, np.nan:0}}, inplace=True)


In [181]:
N = len(X.PassengerId)
x = np.empty((N, 2), dtype=int)
for i in range(N):
    x[i] = (X.PassengerId[i], y_pred_rf[i])
x

array([[ 892,    0],
       [ 893,    1],
       [ 894,    1],
       [ 895,    1],
       [ 896,    0],
       [ 897,    0],
       [ 898,    0],
       [ 899,    0],
       [ 900,    1],
       [ 901,    1],
       [ 902,    1],
       [ 903,    1],
       [ 904,    0],
       [ 905,    0],
       [ 906,    0],
       [ 907,    1],
       [ 908,    0],
       [ 909,    1],
       [ 910,    0],
       [ 911,    1],
       [ 912,    0],
       [ 913,    1],
       [ 914,    1],
       [ 915,    1],
       [ 916,    0],
       [ 917,    1],
       [ 918,    0],
       [ 919,    0],
       [ 920,    1],
       [ 921,    0],
       [ 922,    0],
       [ 923,    1],
       [ 924,    1],
       [ 925,    0],
       [ 926,    0],
       [ 927,    0],
       [ 928,    1],
       [ 929,    0],
       [ 930,    0],
       [ 931,    1],
       [ 932,    0],
       [ 933,    0],
       [ 934,    0],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    0],
       [ 939,

In [ ]:
np.to_csv(x, "./kaggle_data/titanic/submission.csv", header=["PassengerId", "Survived"], index=False)

(418, 2)